name: Daily Database Update

on:
  schedule:
    # Run at 1:00 UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update market data
        run: python scripts/update_data.py
      
      - name: Train models
        run: python scripts/train_models.py
      
      - name: Sync to SQLite Cloud
        env:
          SQLITECLOUD_URL: ${{ secrets.SQLITECLOUD_URL }}
          USE_SQLITECLOUD: "1"
        run: python scripts/sync_to_cloud.py
      
      - name: Commit and push changes to local database
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/market_data.db
          git commit -m "Update market data and predictions" || echo "No changes to commit"
          git push
